### ISSUE TITLE
AssertionError: Rendering dt (0.03333333333333333) must be a multiple of physics dt (0.01)

### ISSUE THREAD

**Issue by SherylSandberg** [huangwl18/ReKep#12]
I'm experiencing a crash when executing the following command:
```bash
python main.py --use_cached_query --visualize
```
The terminal output indicates the following warnings and an error traceback:

```
2024-10-09 11:40:21 [8,580ms] [Warning] [omni.particle.system.core.scripts.extension] 
            ATTENTION!: omni.particle.system.core is currently undergoing extensive (breaking) changes.
            Please be aware that systems built with the existing extension will need to be rebuilt in
            the USD Composer 2023.2 release.
[8.597s] [ext: omni.kit.browser.folder.core-1.9.12] startup
[8.605s] [ext: omni.particle.system.ui-105.1.10] startup
[8.708s] [ext: omni.graph.window.particle.system-105.1.18] startup
DYNAMICS_TODO:
  Make sure "omni.particle.system.core2" is a proper dependency.
  For now, it can just be set to autoload.
DYNAMICS_TODO:
  Make sure "omni.particle.system.core2" is a proper dependency.
  For now, it can just be set to autoload.
[8.742s] [ext: omni.particle.system.bundle-105.1.0] startup
Traceback (most recent call last):
  File "/home/ariel/ReKep/main.py", line 379, in <module>
    main = Main(scene_file, visualize=args.visualize)
  File "/home/ariel/ReKep/main.py", line 40, in __init__
    self.env = ReKepOGEnv(global_config['env'], scene_file, verbose=False)
  File "/home/ariel/ReKep/environment.py", line 69, in __init__
    self.og_env = og.Environment(dict(scene=self.config['scene'], robots=[self.config['robot']['robot_config']], env=self.config['og_sim']))
  File "/home/ariel/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/utils/python_utils.py", line 93, in wrapper
    func(*values.args, **values.kwargs)
  File "/home/ariel/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_base.py", line 103, in __init__
    og.launch(
  File "/home/ariel/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 1780, in _launch_simulator
    Simulator(*args, **kwargs)
  File "/home/ariel/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 295, in __init__
    self._validate_dts(physics_dt, rendering_dt, sim_step_dt)
  File "/home/ariel/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 508, in _validate_dts
    assert math.isclose(
AssertionError: Rendering dt (0.03333333333333333) must be a multiple of physics dt (0.01)
2024-10-09 11:40:21 [8,742ms] [Warning] [carb] [Plugin: omni.sensors.tiled.plugin] Module /home/ariel/miniconda3/envs/omnigibson/lib/python3.10/site-packages/isaacsim/extscache/omni.sensors.tiled-0.0.4+106.0.0.lx64.r/bin/libomni.sensors.tiled.plugin.so remained loaded after unload request
2024-10-09 11:40:21 [8,747ms] [Warning] [carb] [Plugin: omni.spectree.delegate.plugin] Module /home/ariel/miniconda3/envs/omnigibson/lib/python3.10/site-packages/isaacsim/extscache/omni.usd_resolver/bin/libomni.spectree.delegate.plugin.so remained loaded after unload request
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-09 11:40:21 [8,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-10-09 11:40:21 [8,753ms] [Warning] [omni.physx.plugin] Detach stage failed!
2024-10-09 11:40:21 [8,895ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
```

**Comment by sumo43** [comment]
in config.yaml, set num physics_frequency=30 or 60

**Comment by SherylSandberg** [comment]
> in config.yaml, set num physics_frequency=30 or 60

Thank you, it works

**Comment by Benxiaogu** [comment]
Hello,my friends! I have the same problem as you, and I set num physics_frequency=30. But after that, I have new problem as follow:
Warning: Possible version incompatibility. Attempting to load omni::fabric::IStageReaderWriter with version v0.10 against v0.9.
2024-11-08 08:42:31 [6,822ms] [Warning] [omni.syntheticdata.plugin] OgnSdPostRenderVarToHost : rendervar copy from texture directly to host buffer is counter-performant. Please use copy from texture to device buffer first.
2024-11-08 08:42:31 [6,904ms] [Warning] [omni.fabric.plugin] removePath called on non-existent path /Render/RenderProduct_Replicator/PostRender/SDGPipeline/RenderProduct_Replicator_GpuInteropEntry 


                   ____________
                  /          / \
                 /          / /__
                /          / /  /\
               /__________/ /__/  \
               \   _____  \ \__\  /
                \  \  / \  \ \_/ /
                 \  \/___\  \   /
                  \__________\_/  
       ___                  _  ____ _ _                     
      / _ \ _ __ ___  _ __ (_)/ ___(_) |__  ___  ___  _ __  
     | | | | '_ ` _ \| '_ \| | |  _| | '_ \/ __|/ _ \| '_ \ 
     | |_| | | | | | | | | | | |_| | | |_) \__ \ (_) | | | |
      \___/|_| |_| |_|_| |_|_|\____|_|_.__/|___/\___/|_| |_|

[INFO] [omnigibson.simulator] ---------- Welcome to OmniGibson! ----------
Traceback (most recent call last):
  File "/home/dawn/workspace/ReKep/main.py", line 379, in <module>
    main = Main(scene_file, visualize=args.visualize)
  File "/home/dawn/workspace/ReKep/main.py", line 40, in __init__
    self.env = ReKepOGEnv(global_config['env'], scene_file, verbose=False)
  File "/home/dawn/workspace/ReKep/environment.py", line 69, in __init__
    self.og_env = og.Environment(dict(scene=self.config['scene'], robots=[self.config['robot']['robot_config']], env=self.config['og_sim']))
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/utils/python_utils.py", line 93, in wrapper
    func(*values.args, **values.kwargs)
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_base.py", line 128, in __init__
    self.load()
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_base.py", line 429, in load
    self._load_scene()
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_base.py", line 257, in _load_scene
    og.sim.import_scene(self._scene)
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 700, in import_scene
    self._last_scene_edge = scene.load(
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/scenes/scene_base.py", line 449, in load
    new_scene_edge = self._load_scene_prim_with_objects(**kwargs)
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/scenes/scene_base.py", line 364, in _load_scene_prim_with_objects
    self.add_object(obj)
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/scenes/scene_base.py", line 630, in add_object
    prim = obj.load(self)
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/objects/object_base.py", line 123, in load
    prim = super().load(scene)
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/prims/prim_base.py", line 116, in load
    self._post_load()
  File "/home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/objects/dataset_object.py", line 234, in _post_load
    assert th.all(scale > 1e-4), f"Scale of {self.name} is too small: {scale}"
TypeError: all() received an invalid combination of arguments - got (bool), but expected one of:
 * (Tensor input, *, Tensor out = None)
 * (Tensor input, tuple of ints dim = None, bool keepdim = False, *, Tensor out = None)
 * (Tensor input, int dim, bool keepdim = False, *, Tensor out = None)
 * (Tensor input, name dim, bool keepdim = False, *, Tensor out = None)

2024-11-08 08:42:32 [8,165ms] [Warning] [carb] [Plugin: omni.sensors.tiled.plugin] Module /home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/isaacsim/extscache/omni.sensors.tiled-0.0.4+106.0.0.lx64.r/bin/libomni.sensors.tiled.plugin.so remained loaded after unload request
2024-11-08 08:42:32 [8,170ms] [Warning] [carb] [Plugin: omni.spectree.delegate.plugin] Module /home/dawn/anaconda3/envs/omnigibson/lib/python3.10/site-packages/isaacsim/extscache/omni.usd_resolver/bin/libomni.spectree.delegate.plugin.so remained loaded after unload request
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-11-08 08:42:32 [8,172ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-11-08 08:42:32 [8,366ms] [Warning] [carb] Client omni.syntheticdata.plugin Failed to acquire interface [omni::graph::core::INode v4.10] while unloading all plugins
Fatal Python error: Segmentation fault

Current thread 0x00007f5637910740 (most recent call first):
  <no Python frame>

Extension modules: mkl._mklinit, mkl._py_mkl_service, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._dynamo.autograd_compiler, torch._C._dynamo.eval_frame, torch._C._dynamo.guards, torch._C._dynamo.utils, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, scipy._lib._ccallback_c, yaml._yaml, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.spatial._ckdtree, scipy._lib.messagestream, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation, scipy.optimize._group_columns, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.optimize._direct, psutil._psutil_linux, psutil._psutil_posix, PIL._imaging, markupsafe._speedups, sklearn.__check_build._check_build, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.interpolate._fitpack, scipy.interpolate._dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.special.cython_special, scipy.stats._stats, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy._lib._uarray._uarray, scipy.stats._ansari_swilk_statistics, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.stats._unuran.unuran_wrapper, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, sklearn.utils._isfinite, sklearn.utils.sparsefuncs_fast, sklearn.utils.murmurhash, sklearn.utils._openmp_helpers, sklearn.metrics.cluster._expected_mutual_info_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.preprocessing._target_encoder_fast, sklearn.metrics._dist_metrics, sklearn.metrics._pairwise_distances_reduction._datasets_pair, sklearn.utils._cython_blas, sklearn.metrics._pairwise_distances_reduction._base, sklearn.metrics._pairwise_distances_reduction._middle_term_computer, sklearn.utils._heap, sklearn.utils._sorting, sklearn.metrics._pairwise_distances_reduction._argkmin, sklearn.metrics._pairwise_distances_reduction._argkmin_classmode, sklearn.utils._vector_sentinel, sklearn.metrics._pairwise_distances_reduction._radius_neighbors, sklearn.metrics._pairwise_distances_reduction._radius_neighbors_classmode, sklearn.metrics._pairwise_fast, sklearn.neighbors._partition_nodes, sklearn.neighbors._ball_tree, sklearn.neighbors._kd_tree, sklearn.utils.arrayfuncs, sklearn.utils._random, sklearn.utils._seq_dataset, sklearn.linear_model._cd_fast, _loss, sklearn._loss._loss, sklearn.svm._liblinear, sklearn.svm._libsvm, sklearn.svm._libsvm_sparse, sklearn.utils._weight_vector, sklearn.linear_model._sgd_fast, sklearn.linear_model._sag_fast, sklearn.decomposition._online_lda_fast, sklearn.decomposition._cdnmf_fast, h5py._errors, h5py.defs, h5py._objects, h5py.h5, h5py.utils, h5py.h5t, h5py.h5s, h5py.h5ac, h5py.h5p, h5py.h5r, h5py._proxy, h5py._conv, h5py.h5z, h5py.h5a, h5py.h5d, h5py.h5ds, h5py.h5g, h5py.h5i, h5py.h5f, h5py.h5fd, h5py.h5pl, h5py.h5o, h5py.h5l, h5py._selector, _cffi_backend, kiwisolver._cext, sklearn.utils._fast_dict, sklearn.cluster._hierarchical_fast, sklearn.cluster._k_means_common, sklearn.cluster._k_means_elkan, sklearn.cluster._k_means_lloyd, sklearn.cluster._k_means_minibatch, sklearn.cluster._dbscan_inner, sklearn.cluster._hdbscan._tree, sklearn.cluster._hdbscan._linkage, sklearn.cluster._hdbscan._reachability, sklearn._isotonic, sklearn.tree._utils, sklearn.tree._tree, sklearn.tree._splitter, sklearn.tree._criterion, sklearn.neighbors._quad_tree, sklearn.manifold._barnes_hut_tsne, sklearn.manifold._utils, _brotli, gmpy2.gmpy2, omni.mdl.pymdlsdk._pymdlsdk, PIL._imagingft, osqp._osqp, multidict._multidict, yarl._quoting_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, frozenlist._frozenlist, scipy.io.matlab._mio_utils, scipy.io.matlab._streams, scipy.io.matlab._mio5_utils (total: 259)
段错误 (核心已转储)

I will appreciate it if you could answer that!

**Comment by Hs-jy** [comment]
in og_scene_file_pen.json, line 897, set "scale"：[2.0,2.0,2.0]

**Comment by Benxiaogu** [comment]
> in og_scene_file_pen.json, line 897, set "scale"：[2.0,2.0,2.0]

sorry, it doesn't work.

**Comment by BateCheaterDemon** [comment]
> [2.0,2.0,2.0]

I also meet this question too,after set like this,I can see the scene,but program crash soon。
2024-12-06 06:11:43 [15,275ms] [Warning] [omni.syntheticdata.plugin] SdRenderVarPtr missing valid input renderVar LdrColorSDhost
[INFO] [omnigibson.simulator] Imported scene 0.
[WARNING] [omnigibson.robots.fetch] Fetch wheel links are post-processed to use sphere approximation collision meshes. Please ignore any previous errors about these collision meshes.
2024-12-06 06:11:47 [18,522ms] [Warning] [omnigibson.robots.fetch] Fetch wheel links are post-processed to use sphere approximation collision meshes. Please ignore any previous errors about these collision meshes.
[WARNING] [omnigibson.robots.fetch] Fetch wheel links are post-processed to use sphere approximation collision meshes. Please ignore any previous errors about these collision meshes.
2024-12-06 06:11:47 [18,523ms] [Warning] [omnigibson.robots.fetch] Fetch wheel links are post-processed to use sphere approximation collision meshes. Please ignore any previous errors about these collision meshes.
/home/ubuntu/OmniGibson/OmniGibson/omnigibson/utils/python_utils.py:730: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  out = th.tensor(nums, dtype=dtype) if isinstance(nums, Iterable) else th.ones(dim, dtype=dtype) * nums
/home/ubuntu/anaconda3/envs/omnigibson/lib/python3.10/site-packages/torch/functional.py:534: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647352509/work/aten/src/ATen/native/TensorShape.cpp:3595.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/ubuntu/OmniGibson/ReKep/main.py", line 379, in <module>
    main = Main(scene_file, visualize=args.visualize)
  File "/home/ubuntu/OmniGibson/ReKep/main.py", line 40, in __init__
    self.env = ReKepOGEnv(global_config['env'], scene_file, verbose=False)
  File "/home/ubuntu/OmniGibson/ReKep/environment.py", line 77, in __init__
    self.world2robot_homo = T.pose_inv(T.pose2mat(self.robot.get_position_orientation()))
  File "/home/ubuntu/OmniGibson/ReKep/transform_utils.py", line 458, in pose2mat
    homo_pose_mat = np.zeros((4, 4), dtype=pose[0].dtype)
TypeError: Cannot interpret 'torch.float32' as a data type

**Comment by Lilac-cc** [comment]
> in config.yaml, set num physics_frequency=30 or 60

Hello, I also met the same question, but after set like this, I met a new question, the terminal output indicates the following warnings and an error traceback: 
'''
[13.073s] [ext: omni.particle.system.bundle-105.1.0] startup
Traceback (most recent call last):
  File "/root/autodl-tmp/ReKep/main.py", line 379, in <module>
    main = Main(scene_file, visualize=args.visualize)
  File "/root/autodl-tmp/ReKep/main.py", line 40, in __init__
    self.env = ReKepOGEnv(global_config['env'], scene_file, verbose=False)
  File "/root/autodl-tmp/ReKep/environment.py", line 69, in __init__
    self.og_env = og.Environment(dict(scene=self.config['scene'], robots=[self.config['robot']['robot_config']], env=self.config['og_sim']))
  File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/utils/python_utils.py", line 93, in wrapper
    func(*values.args, **values.kwargs)
  File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_base.py", line 103, in __init__
    og.launch(
  File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 1780, in _launch_simulator
    Simulator(*args, **kwargs)
  File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 295, in __init__
    self._validate_dts(physics_dt, rendering_dt, sim_step_dt)
  File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 524, in _validate_dts
    assert sim_step_dt == rendering_dt, (
AssertionError: Simulation step dt (0.06666666666666667) must be equal to rendering dt (0.03333333333333333) when gm.HEADLESS is set!
'''

I wonder how I should do to solve this problem, thank you!

**Comment by VincentWanghh** [comment]
> > in config.yaml, set num physics_frequency=30 or 60
> 
> Hello, I also met the same question, but after set like this, I met a new question, the terminal output indicates the following warnings and an error traceback:
> 
> ```
> [13.073s] [ext: omni.particle.system.bundle-105.1.0] startup
> Traceback (most recent call last):
>   File "/root/autodl-tmp/ReKep/main.py", line 379, in <module>
>     main = Main(scene_file, visualize=args.visualize)
>   File "/root/autodl-tmp/ReKep/main.py", line 40, in __init__
>     self.env = ReKepOGEnv(global_config['env'], scene_file, verbose=False)
>   File "/root/autodl-tmp/ReKep/environment.py", line 69, in __init__
>     self.og_env = og.Environment(dict(scene=self.config['scene'], robots=[self.config['robot']['robot_config']], env=self.config['og_sim']))
>   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/utils/python_utils.py", line 93, in wrapper
>     func(*values.args, **values.kwargs)
>   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_base.py", line 103, in __init__
>     og.launch(
>   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 1780, in _launch_simulator
>     Simulator(*args, **kwargs)
>   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 295, in __init__
>     self._validate_dts(physics_dt, rendering_dt, sim_step_dt)
>   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 524, in _validate_dts
>     assert sim_step_dt == rendering_dt, (
> AssertionError: Simulation step dt (0.06666666666666667) must be equal to rendering dt (0.03333333333333333) when gm.HEADLESS is set!
> ```
> 
> I wonder how I should do to solve this problem, thank you!

I met the same problem. Could I ask you whether you have solved this problem? Thanks :)

**Comment by Quest2GM** [comment]
@VincentWanghh @Lilac-cc @BateCheaterDemon @Benxiaogu. Use this repository: https://github.com/Bailey-24/Rekep

**Comment by Lilac-cc** [comment]
> @VincentWanghh @Lilac-cc @BateCheaterDemon @Benxiaogu. Use this repository: https://github.com/Bailey-24/Rekep

Sorry, it doesn't work out neither.

**Comment by Lilac-cc** [comment]
Sorry, I haven't solved it yet.&nbsp;If you work it out, could you please share the solution with me? Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huangwl18/ReKep"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月27日(星期五) 中午1:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huangwl18/ReKep] AssertionError: Rendering dt (0.03333333333333333) must be a multiple of physics dt (0.01) (Issue #12)





   
in config.yaml, set num physics_frequency=30 or 60
  
Hello, I also met the same question, but after set like this, I met a new question, the terminal output indicates the following warnings and an error traceback:
 [13.073s] [ext: omni.particle.system.bundle-105.1.0] startup Traceback (most recent call last):   File "/root/autodl-tmp/ReKep/main.py", line 379, in <module&gt;     main = Main(scene_file, visualize=args.visualize)   File "/root/autodl-tmp/ReKep/main.py", line 40, in __init__     self.env = ReKepOGEnv(global_config['env'], scene_file, verbose=False)   File "/root/autodl-tmp/ReKep/environment.py", line 69, in __init__     self.og_env = og.Environment(dict(scene=self.config['scene'], robots=[self.config['robot']['robot_config']], env=self.config['og_sim']))   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/utils/python_utils.py", line 93, in wrapper     func(*values.args, **values.kwargs)   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/envs/env_base.py", line 103, in __init__     og.launch(   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 1780, in _launch_simulator     Simulator(*args, **kwargs)   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 295, in __init__     self._validate_dts(physics_dt, rendering_dt, sim_step_dt)   File "/root/miniconda3/envs/omnigibson/lib/python3.10/site-packages/omnigibson/simulator.py", line 524, in _validate_dts     assert sim_step_dt == rendering_dt, ( AssertionError: Simulation step dt (0.06666666666666667) must be equal to rendering dt (0.03333333333333333) when gm.HEADLESS is set!  
I wonder how I should do to solve this problem, thank you!
  
I met the same problem. Could I ask you whether you have solved this problem? Thanks :)

**Comment by Benxiaogu** [comment]
> @VincentWanghh @Lilac-cc @BateCheaterDemon @Benxiaogu. Use this repository: https://github.com/Bailey-24/Rekep

Thank you. It works!

**Comment by ursulalujun** [comment]
@curry2736 @VincentWanghh From the comment and assert, we know that rendering_dt and sim_step_dt need to be set the same, so we can set rendering_dt to 15 when init Simulator.

![Image](https://github.com/user-attachments/assets/2ad72746-b97e-4922-b328-f8d83405f4a7)

![Image](https://github.com/user-attachments/assets/28f6b4a8-4f0b-4dd5-84aa-a2b886b2264b)
