### ISSUE TITLE
一些问题的总结

### ISSUE THREAD

**Issue by Gutilence14** [huangwl18/ReKep#13]
1、AssertionError: Rendering dt (0.03333333333333333) must be a multiple of physics dt (0.01)
把config.yaml中的physics_frequency改成30
2、assert th.all(scale > 1e-4), f"Scale of {self.name} is too small: {scale}"
把og_scene_file_pen.json第897行的scale改成[2.0,2.0,2.0]
3、后续各种数据类型问题
把所有的Tensor改成numpy即可

我还遇到一个问题暂时无法解决，但是不影响使用
打开仿真器之前会报错无法链接到动态库，希望有缘人解答
![图片](https://github.com/user-attachments/assets/2325115b-6f1e-45de-9576-aaaae81b4ace)

**Comment by Bailey-24** [comment]
哈喽，哥们，我运行python main.py --use_cached_query，
但一开始笔会直接掉到桌子下面，你有遇到吗，怎么解决比较好。
![image](https://github.com/user-attachments/assets/d6229067-ece3-43dd-a84e-ed50c7392e90)

**Comment by Gutilence14** [comment]
> 哈喽，哥们，我运行python main.py --use_cached_query， 但一开始笔会直接掉到桌子下面，你有遇到吗，怎么解决比较好。 ![image](https://private-user-images.githubusercontent.com/72083251/375926111-d6229067-ece3-43dd-a84e-ed50c7392e90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTE0MDIsIm5iZiI6MTcyODcxMTEwMiwicGF0aCI6Ii83MjA4MzI1MS8zNzU5MjYxMTEtZDYyMjkwNjctZWNlMy00M2RkLWE4NGUtZWQ1MGM3MzkyZTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA1MzE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZmM5NmFiOGU2NjFmNzMzOGY5NmQxYzFmMGNiYjM5MTRlNmY4YmNkM2FiMTI0MTJjYWQ0NTZjYjQ4MzcyZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.awkLsF0Lkc9uuSMpoihe5YhuXdeJW4NvVuxptRwuSkk)

没遇到这个问题，但是应该是场景初始化的坐标有问题，可以在那个json文件里的坐标随便改改试试

**Comment by Bailey-24** [comment]
嗯嗯，
json那里改成
```
            "pen_1": {
                "root_link": {
                    "pos": [
                        -0.30,
                        -0.15,
                        0.7163046002388
                    ],
                    "ori": [ -0.7071068, 0, 0, 0.7071068 ],
                    "lin_vel": [
                        0.0,
                        0.0,
                        0.0
                    ],
                    "ang_vel": [
                        0.0,
                        0.0,
                        0.0
                    ]
                },
                "joints": {},
                "non_kin": {}
            },
```
就好了

**Comment by Bailey-24** [comment]
https://zhuanlan.zhihu.com/p/945556099

**Comment by charon87** [comment]
> 知乎版，复现debug过程
> 
> [https://zhuanlan.zhihu.com/p/945556099。](https://zhuanlan.zhihu.com/p/945556099%E3%80%82)
> 
> 或者git clone https://github.com/Bailey-24/Rekep
![截图 2024-10-28 16-43-35](https://github.com/user-attachments/assets/b75a3779-add8-4e86-8a34-509e42fd2acd)
您好，我是一个新手菜鸟，非常感谢您将修改后的代码开源，少走了很多弯路，谢谢您！现在我在ubuntu22.04系统上运行python main.py --visualize 会出现图片里的情况，一直卡在获取关键点后，之后就一直无响应，请问您有什么建议的解决方案吗？我运行python main.py --use_cached_query --visualize是正常的。

**Comment by charon87** [comment]
> > 知乎版，复现debug过程
> > [https://zhuanlan.zhihu.com/p/945556099。](https://zhuanlan.zhihu.com/p/945556099%E3%80%82)
> > 或者git clone https://github.com/Bailey-24/Rekep
> > ![截图 2024-10-28 16-43-35](https://private-user-images.githubusercontent.com/118268550/380638324-b75a3779-add8-4e86-8a34-509e42fd2acd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDU1OTcsIm5iZiI6MTczMDEwNTI5NywicGF0aCI6Ii8xMTgyNjg1NTAvMzgwNjM4MzI0LWI3NWEzNzc5LWFkZDgtNGU4Ni04YTM0LTUwOWU0MmZkMmFjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQwODQ4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDVjYzk3ZTBlMmE0MTI0ZGZmYTVhOTc1NTA3M2EwMTE4N2UyMzRjMmNiOTY4OWM4YjJmNjZmYWI0NWE1ZmYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hXQ8JM4YH_ELLEFj3iJXsYX0PyuvZG1Jo4r-NSh2ByQ)
> > 您好，我是一个新手菜鸟，非常感谢您将修改后的代码开源，少走了很多弯路，谢谢您！现在我在ubuntu22.04系统上运行python main.py --visualize 会出现图片里的情况，一直卡在获取关键点后，之后就一直无响应，请问您有什么建议的解决方案吗？我运行python main.py --use_cached_query --visualize是正常的。

@Bailey-24

**Comment by wzl1026** [comment]
你好，可以加您给联系方式吗，我和您有相同的问题，可以请教一下您吗

**Comment by Bailey-24** [comment]
18026868507



发自我的iPhone


------------------ 原始邮件 ------------------
From: charon87 ***@***.***&gt;
发送时间: 10/28/2024, 16:49
To: huangwl18/ReKep ***@***.***&gt;
抄送: Jiahui Zhu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [huangwl18/ReKep] 一些问题的总结 (Issue #13)





   
知乎版，复现debug过程
 https://zhuanlan.zhihu.com/p/945556099。
 或者git clone https://github.com/Bailey-24/Rekep
 
 您好，我是一个新手菜鸟，非常感谢您将修改后的代码开源，少走了很多弯路，谢谢您！现在我在ubuntu22.04系统上运行python main.py --visualize 会出现图片里的情况，一直卡在获取关键点后，之后就一直无响应，请问您有什么建议的解决方案吗？我运行python main.py --use_cached_query --visualize是正常的。
   
@Bailey-24

**Comment by Bailey-24** [comment]
18026868507



发自我的iPhone


------------------ 原始邮件 ------------------
From: wzl1026 ***@***.***&gt;
发送时间: 10/30/2024, 09:28
To: huangwl18/ReKep ***@***.***&gt;
抄送: Jiahui Zhu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [huangwl18/ReKep] 一些问题的总结 (Issue #13)





 
你好，可以加您给联系方式吗，我和您有相同的问题，可以请教一下您吗

**Comment by coutendlsdsd** [comment]
> 知乎版，复现debug过程
> 
> [https://zhuanlan.zhihu.com/p/945556099。](https://zhuanlan.zhihu.com/p/945556099%E3%80%82)
> 
> 或者git clone https://github.com/Bailey-24/Rekep

Traceback (most recent call last):
  File "E:\Rekep\main.py", line 379, in <module>
    main = Main(scene_file, visualize=args.visualize)
  File "E:\Rekep\main.py", line 51, in __init__
    self.subgoal_solver = SubgoalSolver(global_config['subgoal_solver'], ik_solver, self.env.reset_joint_pos)
  File "E:\Rekep\subgoal_solver.py", line 124, in __init__
    self._warmup()
  File "E:\Rekep\subgoal_solver.py", line 134, in _warmup
    self.solve(ee_pose, keypoints, keypoint_movable_mask, goal_constraints, path_constraints, sdf_voxels, collision_points, True, None, from_scratch=True)
  File "E:\Rekep\subgoal_solver.py", line 253, in solve
    opt_result = dual_annealing(
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\scipy\_lib\_util.py", line 440, in wrapper
    return fun(*args, **kwargs)
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\scipy\optimize\_dual_annealing.py", line 674, in dual_annealing
    energy_state.reset(func_wrapper, rng_gen, x0)
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\scipy\optimize\_dual_annealing.py", line 173, in reset
    self.current_energy = func_wrapper.fun(self.current_location)
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\scipy\optimize\_dual_annealing.py", line 381, in fun
    return self.func(x, *self.args)
  File "E:\Rekep\subgoal_solver.py", line 39, in objective
    collision_cost = 0.8 * calculate_collision_cost(opt_pose_homo[None], sdf_func, collision_points_centered, 0.10)
  File "E:\Rekep\utils.py", line 36, in calculate_collision_cost
    transformed_pcs = batch_transform_points(collision_points, poses)
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\dispatcher.py", line 442, in _compile_for_args
    raise e
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\dispatcher.py", line 375, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\dispatcher.py", line 886, in compile
    cres = self._cache.load_overload(sig, self.targetctx)
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\caching.py", line 633, in load_overload
    target_context.refresh()
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\base.py", line 277, in refresh
    self.typing_context.refresh()
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\typing\context.py", line 158, in refresh
    self.load_additional_registries()
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\typing\context.py", line 745, in load_additional_registries
    from . import (
  File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\typing\cffi_utils.py", line 19, in <module>
    ffi = cffi.FFI()
  File "c:/users/xiachenglei/miniconda3/envs/omnigibson/lib/site-packages/isaacsim/extscache/omni.kit.pip_archive/pip_prebundle/cffi/api.py", line 54, in __init__
    raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
Exception: Version mismatch: this is the 'cffi' package version 1.16.0, located in 'c:/users/xiachenglei/miniconda3/envs/omnigibson/lib/site-packages/isaacsim/extscache/omni.kit.pip_archive/pip_prebundle/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.17.1, located in 'C:\\Users\\xiachenglei\\miniconda3\\envs\\omnigibson\\lib\\site-packages\\_cffi_backend.cp310-win_amd64.pyd'.  The two versions should be equal; check your installation.

大佬，我是出现了这个问题想问下咋解决的

**Comment by wzmsltw** [comment]
> > 知乎版，复现debug过程
> > [https://zhuanlan.zhihu.com/p/945556099。](https://zhuanlan.zhihu.com/p/945556099%E3%80%82)
> > 或者git clone https://github.com/Bailey-24/Rekep
> 
> Traceback (most recent call last): File "E:\Rekep\main.py", line 379, in main = Main(scene_file, visualize=args.visualize) File "E:\Rekep\main.py", line 51, in **init** self.subgoal_solver = SubgoalSolver(global_config['subgoal_solver'], ik_solver, self.env.reset_joint_pos) File "E:\Rekep\subgoal_solver.py", line 124, in **init** self._warmup() File "E:\Rekep\subgoal_solver.py", line 134, in _warmup self.solve(ee_pose, keypoints, keypoint_movable_mask, goal_constraints, path_constraints, sdf_voxels, collision_points, True, None, from_scratch=True) File "E:\Rekep\subgoal_solver.py", line 253, in solve opt_result = dual_annealing( File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\scipy_lib_util.py", line 440, in wrapper return fun(*args, **kwargs) File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\scipy\optimize_dual_annealing.py", line 674, in dual_annealing energy_state.reset(func_wrapper, rng_gen, x0) File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\scipy\optimize_dual_annealing.py", line 173, in reset self.current_energy = func_wrapper.fun(self.current_location) File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\scipy\optimize_dual_annealing.py", line 381, in fun return self.func(x, *self.args) File "E:\Rekep\subgoal_solver.py", line 39, in objective collision_cost = 0.8 * calculate_collision_cost(opt_pose_homo[None], sdf_func, collision_points_centered, 0.10) File "E:\Rekep\utils.py", line 36, in calculate_collision_cost transformed_pcs = batch_transform_points(collision_points, poses) File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\dispatcher.py", line 442, in _compile_for_args raise e File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\dispatcher.py", line 375, in _compile_for_args return_val = self.compile(tuple(argtypes)) File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\dispatcher.py", line 886, in compile cres = self._cache.load_overload(sig, self.targetctx) File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\caching.py", line 633, in load_overload target_context.refresh() File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\base.py", line 277, in refresh self.typing_context.refresh() File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\typing\context.py", line 158, in refresh self.load_additional_registries() File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\typing\context.py", line 745, in load_additional_registries from . import ( File "C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\numba\core\typing\cffi_utils.py", line 19, in ffi = cffi.FFI() File "c:/users/xiachenglei/miniconda3/envs/omnigibson/lib/site-packages/isaacsim/extscache/omni.kit.pip_archive/pip_prebundle/cffi/api.py", line 54, in **init** raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r. When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r. The two versions should be equal; check your installation." % ( Exception: Version mismatch: this is the 'cffi' package version 1.16.0, located in 'c:/users/xiachenglei/miniconda3/envs/omnigibson/lib/site-packages/isaacsim/extscache/omni.kit.pip_archive/pip_prebundle/cffi/api.py'. When we import the top-level '_cffi_backend' extension module, we get version 1.17.1, located in 'C:\Users\xiachenglei\miniconda3\envs\omnigibson\lib\site-packages\_cffi_backend.cp310-win_amd64.pyd'. The two versions should be equal; check your installation.
> 
> 大佬，我是出现了这个问题想问下咋解决的

@coutendlsdsd 你好，请问你有解决这个问题了嘛？
