### ISSUE TITLE
python main.py --visualize can not run

### ISSUE THREAD

**Issue by wzl1026** [huangwl18/ReKep#22]
hello everyone,i can run python main.py --use_cached_query --visualize，but i cant run python main.py --visualize , my api_key can use, there is my wrong:
Traceback (most recent call last):
  File "C:\Windows\Rekep\main.py", line 380, in <module>
    main.perform_task(instruction,
  File "C:\Windows\Rekep\main.py", line 72, in perform_task
    rekep_program_dir = self.constraint_generator.generate(projected_img, instruction, metadata)
  File "C:\Windows\Rekep\constraint_generation.py", line 138, in generate
    stream = self.client.chat.completions.create(model=self.config['model'],
  File "E:\Anaconda\envs\omnigibson\lib\site-packages\openai\_utils\_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "E:\Anaconda\envs\omnigibson\lib\site-packages\openai\resources\chat\completions.py", line 815, in create
    return self._post(
  File "E:\Anaconda\envs\omnigibson\lib\site-packages\openai\_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "E:\Anaconda\envs\omnigibson\lib\site-packages\openai\_base_client.py", line 954, in request
    return self._request(
  File "E:\Anaconda\envs\omnigibson\lib\site-packages\openai\_base_client.py", line 1058, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'wrong api key', 'type': 'chatanywhere_error', 'param': None, 'code': '401 UNAUTHORIZED'}}

**Comment by goodrain553** [comment]
it seems like your openAI_key is wrong. So the website returns 401.

**Comment by wzl1026** [comment]
but i have a test program to test my key ,it works, but after i set the key to env, i cant run --python main.py, do you have some ideas  bro?

**Comment by coutendlsdsd** [comment]
> but i have a test program to test my key ,it works, but after i set the key to env, i cant run --python main.py, do you have some ideas bro?

I have the same problem

**Comment by rainingTD** [comment]
I have the same issue, is there any workaround
