### ISSUE TITLE
Isaac-Sim 4.2 和 4.1版本运行问题

### ISSUE THREAD

**Issue by YunLongPan** [huangwl18/ReKep#9]
大佬您好，我在运行demo代码 python main.py --use_cached_query 出现以下报错：
我是在Isaac-Sim 4.2和4.1上运行，请问是否因为sim版本的原因呢？

[22.782s] [ext: omni.graph.window.particle.system-105.1.18] startup
DYNAMICS_TODO:
  Make sure "omni.particle.system.core2" is a proper dependency.
  For now, it can just be set to autoload.
DYNAMICS_TODO:
  Make sure "omni.particle.system.core2" is a proper dependency.
  For now, it can just be set to autoload.
[22.890s] [ext: omni.particle.system.bundle-105.1.0] startup
Traceback (most recent call last):
  File "/home/pci/桌面/ReKep/main.py", line 379, in <module>
    main = Main(scene_file, visualize=args.visualize)
  File "/home/pci/桌面/ReKep/main.py", line 40, in __init__
    self.env = ReKepOGEnv(global_config['env'], scene_file, verbose=False)
  File "/home/pci/桌面/ReKep/environment.py", line 69, in __init__
    self.og_env = og.Environment(dict(scene=self.config['scene'], robots=[self.config['robot']['robot_config']], env=self.config['og_sim']))
  File "/home/pci/桌面/OmniGibson/omnigibson/utils/python_utils.py", line 93, in wrapper
    func(*values.args, **values.kwargs)
  File "/home/pci/桌面/OmniGibson/omnigibson/envs/env_base.py", line 103, in __init__
    og.launch(
  File "/home/pci/桌面/OmniGibson/omnigibson/simulator.py", line 1780, in _launch_simulator
    Simulator(*args, **kwargs)
  File "/home/pci/桌面/OmniGibson/omnigibson/simulator.py", line 295, in __init__
    self._validate_dts(physics_dt, rendering_dt, sim_step_dt)
  File "/home/pci/桌面/OmniGibson/omnigibson/simulator.py", line 508, in _validate_dts
    assert math.isclose(
AssertionError: Rendering dt (0.03333333333333333) must be a multiple of physics dt (0.01)
2024-10-06 11:12:02 [22,877ms] [Warning] [carb] [Plugin: omni.sensors.tiled.plugin] Module /home/pci/software/anaconda3/envs/rpk/lib/python3.10/site-packages/isaacsim/extscache/omni.sensors.tiled-0.0.4+106.0.0.lx64.r/bin/libomni.sensors.tiled.plugin.so remained loaded after unload request
2024-10-06 11:12:02 [22,890ms] [Warning] [carb] [Plugin: omni.spectree.delegate.plugin] Module /home/pci/software/anaconda3/envs/rpk/lib/python3.10/site-packages/isaacsim/extscache/omni.usd_resolver/bin/libomni.spectree.delegate.plugin.so remained loaded after unload request
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-06 11:12:02 [22,898ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-10-06 11:12:02 [22,905ms] [Warning] [omni.physx.plugin] Detach stage failed!
2024-10-06 11:12:02 [23,036ms] [Warning] [carb] Recursive unloadAllPlugins() detected!

**Comment by ge79puv** [comment]
您好，我也遇到了和您一模一样的问题，请问你是怎么解决的呢？
